### ISSUE TITLE
Version 0.4.0 not working

### ISSUE THREAD

**Issue by gagarinfan** [mumoshu/aws-secret-operator#45]
Hi! I've been using your operator (which is great and very useful) version `0.3.3` and after change to `0.4.0` seems that it has stopped working both for `stringDataFrom` and `dataFrom` options. Latest version has support for base64 secrets (https://github.com/mumoshu/aws-secret-operator/pull/43) which I'd like to use.

Steps to reproduce (example for `stringDataFrom` option):
- EKS version 1.20
- create secret in AWS Secrets Manager. In my case it's `debug-secret` with Secret Key: `key` and Secret Value: `value`
![image](https://user-images.githubusercontent.com/44444839/123619871-e5677500-d809-11eb-82a8-3cabb38f54cf.png)
- create AWSSecret object, for example:
```yaml
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: debug-secret
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: debug-secret
```
- aws-secret-operator creates opaque secret `debug-secret` with empty data field (I've deleted irrelevant lines):
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: debug-secret
  namespace: debug
type: Opaque
data: {}
```
operator logs
```
{"level":"info","ts":1624874936.1018052,"logger":"controller_awssecret","msg":"Secret does not exist, Creating a new Secret","Request.Namespace":"debug","Request.Name":"debug-secret","desired.Namespace":"debug","desired.Name":"debug-secret"}
{"level":"info","ts":1624874936.1154666,"logger":"controller_awssecret","msg":"Secret Created successfully, RequeueAfter 5 minutes","Request.Namespace":"debug","Request.Name":"debug-secret"}

I would be grateful for help
