### ISSUE TITLE
Apply metadata to created secret

### ISSUE THREAD

**Issue by mruoss** [mumoshu/aws-secret-operator#46]
Hi

I created an AwsSecret with labels and annotations, hoping these would be copied over to the created Secret. This seems not to be the case but would be crucial in some cases!

Thanks,
Michael

**Comment by RopoMen** [comment]
This would allow label selector usage in resource deletion https://jamesdefabia.github.io/docs/user-guide/kubectl/kubectl_delete/

Now secrets created by aws-secret-operator needs to be cleaned up manually.

**Comment by mumoshu** [comment]
This sounds like a good idea. One question though. Should it just propagate AWSSecret labels, or should we add another CRD field (like `spec.secretLabels` or `spec.template.metadata.labels`) to deal with the case that you want different sets of labels for AWSSecret and Secret respectively?

**Comment by parraletz** [comment]
taking the case where you need to add the type of secret, I think it would be another CRD field.

I mean:

```
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: example
spec:
  type: kubernetes.io/tls
  secretLabels: 
       argocd.argoproj.io/secret-type: repo-creds
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: prod/mysecret
      versionId: c43e66cb-d0fe-44c5-9b7e-d450441a04be
```

It will create something like that:

```
apiVersion: v1
kind: Secret
metadata:
  name: example
  labels:  
      argocd.argoproj.io/secret-type: repo-creds
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
type: kubernetes.io/tls
```
