### ISSUE TITLE
map a secret as one json file instead of separate key-value pairs

### ISSUE THREAD

**Issue by ulrichwinter** [mumoshu/aws-secret-operator#73]
When I create a secret manually e.g. using:
`kubectl create secret generic test-secret --namespace epi-dev --from-file=some-file.json`
and map the resulting secret as a volume into a pod, then the pod will see a file named `some-file.json` in the mapped location.

How can I achieve the same with aws-secret-operator:
Getting the secret value of the AWS Secret as one whole json file in the pod?

Looking into the resulting kubernetes secret, the difference is just the filename within the data like here:

```
apiVersion: v1
data:
  some-file.json: base64-encoded-json-content....
kind: Secret
metadata:
  name: test-secret
type: Opaque

```
